version: '3.8'

services:
  coral-automatic-segmentation-cuda:
    build:
      context: .
      dockerfile: Dockerfile-cuda
    image: coral-automatic-segmentation-cuda
    container_name: coral-automatic-segmentation-cuda
    ports:
      - "7000:7000"
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://coral.ni.dfki.de,http://localhost:8000,http://0.0.0.0/8000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 7000
